name: slides
description: A slides project for the talk.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_deck: ^0.8.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.1.0
  purrfect_match:
    path: ../app

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/feature-toggling/
    - assets/intro/
    - assets/ab-testing/
    - assets/app-configuration/
