name: purrfect_match
description: A demo project for the talk.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  camera: ^0.10.5+4
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_remote_config: ^4.2.5
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cats/
